In [1]:
# Importing the libraries
import os
import pickle
import re
import string
import warnings

import matplotlib.pyplot as plt
import nltk
import numpy as np
import pandas as pd
from nltk.corpus import stopwords
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score, f1_score, precision_score,
                             recall_score)
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import FeatureUnion, Pipeline
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

%matplotlib inline
warnings.filterwarnings('ignore')

In [2]:
np.random.seed(42)

In [3]:
# Creating list of english stopwords
stopwords_list = list(stopwords.words('english'))
stopwords_list

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [4]:
# Helper function to display the evaluation metrics of the different models
def show_eval_scores(model, test_set, model_name):
    """Function to show to different evaluation score of the model passed
    on the test set.
    
    Parameters:
    -----------
    model: scikit-learn object
        The model whose scores are to be shown.
    test_set: pandas dataframe
        The dataset on which the score of the model is to be shown.
    model_name: string
        The name of the model.
    """
    y_pred = model.predict(test_set)
    y_true = test_set['label']
    f1 = f1_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    accuracy = accuracy_score(y_true, y_pred)

    print('Report for ---> {}'.format(model_name))
    print('Accuracy is: {}'.format(accuracy))
    print('F1 score is: {}'.format(f1))
    print('Precision score is: {}'.format(precision))
    print('Recall score is: {}'.format(recall))

In [5]:
# Importing the datasets
train_data = pd.read_csv('./datasets/train.csv')
valid_data = pd.read_csv('./datasets/valid.csv')
test_data = pd.read_csv('./datasets/test.csv')

Viewing random samples of all datasets

In [6]:
train_data.sample(5)

       label                                               news
3842    True  Polling shows that nearly 74 percent of Nation...
6480   False      I left the city with $43 million in the bank.
4521   False  Says she couldn't take stimulus money because ...
4026    True  The United States is the only industrialized c...
10111  False  The Health Care and Education Reconciliation A...

In [7]:
valid_data.sample(5)

      label                                               news
824    True         Al-Qaida has grown fourfold in five years.
548    True  Under the clear letter of the law, (Justice Cl...
870    True  For immigrants with visa overstays, we make no...
1047   True  The governors budget proposal reduces the stat...
1155   True  Says the director of NASA says its main missio...

In [8]:
test_data.sample(5)

     label                                               news
38    True  The Fed created $1.2 trillion out of nothing, ...
734   True  Says Rick Scott stripped women of access to pu...
138   True  Says NFL Commissioner Roger Goodell interviewe...
128   True  The federal government reviewed and verified h...
700   True  In 1981, Matagorda, Brazoria, and Galveston Co...

In [9]:
print('Train dataset size: {}'.format(train_data.shape))
print('Valid dataset size: {}'.format(valid_data.shape))
print('Test dataset size: {}'.format(test_data.shape))

Train dataset size: (10240, 2)
Valid dataset size: (1284, 2)
Test dataset size: (1267, 2)

Combining train_data and valid_data into a single training set as GridSearchCV with 5 fold cross validation will be used for hyperparameter tuning the different models

In [10]:
training_set = pd.concat([train_data, valid_data], ignore_index=True)
print('Training set size: {}'.format(training_set.shape))
training_set.sample(5)

Training set size: (11524, 2)

      label                                               news
493    True  Says President Obama has cracked down on emplo...
9003  False  It is truethat we know that ISIS is present in...
9892  False  State budget cuts for local schools resulted i...
4184   True  Under the presidents plan, he cuts Medicare by...
8571  False  The last time there was a sustained surge of c...

Creating a TfidfVectorizer object and analyzing the training set

In [11]:
tfidf_V = TfidfVectorizer(stop_words=stopwords_list, use_idf=True, smooth_idf=True)
train_count = tfidf_V.fit_transform(training_set['news'].values)

In [12]:
tfidf_V.vocabulary_

{'says': 10132,
 'annies': 1091,
 'list': 6952,
 'political': 8770,
 'group': 5358,
 'supports': 11218,
 'third': 11550,
 'trimester': 11816,
 'abortions': 648,
 'demand': 3436,
 'decline': 3339,
 'coal': 2589,
 'start': 10919,
 'started': 10920,
 'natural': 7777,
 'gas': 5084,
 'took': 11651,
 'begin': 1601,
 'president': 8956,
 'george': 5138,
 'bushs': 2049,
 'administration': 786,
 'hillary': 5644,
 'clinton': 2555,
 'agrees': 890,
 'john': 6419,
 'mccain': 7300,
 'voting': 12295,
 'give': 5186,
 'bush': 2047,
 'benefit': 1638,
 'doubt': 3859,
 'iran': 6277,
 'health': 5553,
 'care': 2189,
 'reform': 9525,
 'legislation': 6810,
 'likely': 6916,
 'mandate': 7155,
 'free': 4955,
 'sex': 10395,
 'change': 2357,
 'surgeries': 11230,
 'economic': 4022,
 'turnaround': 11876,
 'end': 4176,
 'term': 11455,
 'chicago': 2416,
 'bears': 1575,
 'starting': 10922,
 'quarterbacks': 9256,
 'last': 6718,
 '10': 21,
 'years': 12678,
 'total': 11672,
 'number': 7959,
 'tenured': 11454,
 'uw': 12130,
 'faculty': 4534,
 'fired': 4749,
 'two': 11898,
 'decades': 3319,
 'jim': 6407,
 'dunnam': 3970,
 'lived': 6963,
 'district': 3760,
 'represents': 9700,
 'person': 8575,
 'stage': 10889,
 'worked': 12613,
 'actively': 743,
 'year': 12676,
 'passing': 8421,
 'along': 997,
 'russ': 10023,
 'feingold': 4644,
 'toughest': 11681,
 'ethics': 4324,
 'since': 10554,
 'watergate': 12389,
 'however': 5779,
 '19': 127,
 'million': 7481,
 'oregon': 8150,
 'lottery': 7031,
 'funds': 5025,
 'port': 8817,
 'newport': 7856,
 'eventually': 4347,
 'land': 6687,
 'new': 7849,
 'noaa': 7892,
 'marine': 7203,
 'operations': 8114,
 'center': 2304,
 'pacific': 8305,
 'gop': 5243,
 'primary': 8993,
 'opponents': 8122,
 'glenn': 5201,
 'grothman': 5350,
 'joe': 6418,
 'leibham': 6825,
 'cast': 2238,
 'compromise': 2743,
 'vote': 12288,
 'cost': 3011,
 '788': 543,
 'higher': 5630,
 'electricity': 4082,
 'costs': 3014,
 'first': 4759,
 'time': 11606,
 'history': 5661,
 'share': 10417,
 'national': 7766,
 'popular': 8804,
 'margin': 7198,
 'smaller': 10636,
 'latino': 6728,
 '2000': 209,
 'nearly': 7792,
 '12': 52,
 'americans': 1034,
 'slipped': 10618,
 'middle': 7453,
 'class': 2514,
 'poverty': 8865,
 'mitt': 7557,
 'romney': 9955,
 'governor': 5264,
 'massachusetts': 7247,
 'didnt': 3603,
 'slow': 10625,
 'rate': 9372,
 'growth': 5367,
 'government': 5261,
 'actually': 752,
 'cut': 3202,
 'economy': 4027,
 'bled': 1750,
 '24': 276,
 'billion': 1699,
 'due': 3951,
 'shutdown': 10512,
 'affordable': 852,
 'act': 734,
 'already': 1000,
 'sense': 10333,
 'waived': 12317,
 'otherwise': 8183,
 'suspended': 11263,
 'election': 4074,
 'november': 7948,
 '63': 481,
 'percent': 8534,
 'american': 1033,
 'people': 8527,
 'chose': 2446,
 '80': 548,
 'young': 12694,
 '75': 528,
 'low': 7046,
 'income': 5972,
 'workers': 12615,
 'opposed': 8126,
 'requirement': 9721,
 'buy': 2066,
 'made': 7090,
 'motorcycles': 7658,
 'said': 10050,
 'provisions': 9181,
 'quote': 9280,
 'disgraceful': 3709,
 'rep': 9663,
 'ron': 9958,
 'kind': 6585,
 'wis': 12557,
 'fellow': 4651,
 'democrats': 3445,
 'went': 12457,
 'spending': 10804,
 'spree': 10854,
 'credit': 3103,
 'card': 2185,
 'maxed': 7285,
 'water': 12384,
 'rates': 9375,
 'manila': 7166,
 'philippines': 8616,
 'raised': 9329,
 '845': 568,
 'subsidiary': 11124,
 'world': 12622,
 'bank': 1487,
 'became': 1582,
 'partial': 8387,
 'owner': 8290,
 'almost': 994,
 '100': 22,
 '000': 1,
 'left': 6797,
 'puerto': 9200,
 'rico': 9862,
 'women': 12595,
 'men': 7385,
 'making': 7128,
 'less': 6842,
 'adjust': 776,
 'inflation': 6065,
 'kitzhaber': 6604,
 'elected': 4072,
 'united': 12018,
 'states': 10935,
 'highest': 5631,
 'corporate': 2989,
 'tax': 11379,
 'best': 1663,
 'auto': 1383,
 'industry': 6040,
 'america': 1032,
 'scott': 10221,
 'walker': 12326,
 'favors': 4609,
 'cutting': 3208,
 '350': 351,
 'families': 4565,
 'children': 2428,
 'wants': 12340,
 'get': 5152,
 'rid': 9864,
 'planned': 8698,
 'parenthood': 8368,
 'dont': 3841,
 'know': 6621,
 'jonathan': 6436,
 'gruber': 5368,
 'hate': 5525,
 'crimes': 3112,
 'muslims': 7721,
 'mosques': 7641,
 'tripled': 11822,
 'paris': 8371,
 'san': 10079,
 'bernardino': 1654,
 'rick': 9861,
 'perry': 8566,
 'never': 7847,
 'lost': 7027,
 'remains': 9622,
 'texas': 11485,
 'governorship': 5266,
 'three': 11571,
 'times': 11609,
 'landslide': 6697,
 'elections': 4075,
 'isis': 6301,
 'supporter': 11214,
 'tweeted': 11890,
 '34': 345,
 'shooting': 10475,
 'began': 1597,
 '45': 406,
 'chattanooga': 2384,
 'tenn': 11445,
 'youth': 12700,
 'unemployment': 11986,
 'minority': 7512,
 'communities': 2689,
 '40': 380,
 'paul': 8455,
 'ryan': 10033,
 'still': 10998,
 'endorsing': 4190,
 'trump': 11848,
 'look': 7009,
 'right': 9879,
 'work': 12612,
 'constantly': 2862,
 'budget': 1987,
 'deficits': 3392,
 'good': 5237,
 'business': 2051,
 'climates': 2548,
 'obama': 7983,
 'going': 5225,
 'come': 2645,
 'next': 7867,
 'several': 10385,
 'months': 7616,
 'youre': 12698,
 'even': 4341,
 'able': 635,
 'burn': 2032,
 'limitedly': 6929,
 'existing': 4421,
 'plants': 8704,
 'taxes': 11382,
 'today': 11625,
 '70': 506,
 'businesses': 2052,
 'pay': 8466,
 'mark': 7205,
 'pryor': 9185,
 'votes': 12294,
 '93': 593,
 'federal': 4629,
 'thinks': 11549,
 'authority': 1376,
 'regulate': 9562,
 'toilet': 11632,
 'seats': 10255,
 'austin': 1367,
 'city': 2494,
 'basically': 1542,
 'doubled': 3856,
 'size': 10578,
 'every': 4351,
 '25': 285,
 'founded': 4918,
 'nuclear': 7954,
 'test': 11474,
 'conducted': 2786,
 'nation': 7765,
 'earth': 4003,
 '054th': 12,
 'five': 4774,
 'permanent': 8556,
 'members': 7379,
 'security': 10280,
 'council': 3020,
 '99': 609,
 'tests': 11482,
 'case': 2226,
 'catastrophic': 2249,
 'event': 4344,
 'atlanta': 1320,
 'area': 1212,
 'offices': 8054,
 'centers': 2307,
 'disease': 3701,
 'control': 2933,
 'prevention': 8979,
 'self': 10308,
 'destruct': 3543,
 'added': 761,
 'trillion': 11814,
 'debt': 3312,
 'weve': 12467,
 'supreme': 11223,
 'court': 3048,
 'justice': 6485,
 'suggested': 11162,
 'cases': 2228,
 'decided': 3328,
 'based': 1536,
 'south': 10749,
 'african': 862,
 'law': 6745,
 'marco': 7193,
 'rubio': 9998,
 'skipped': 10588,
 '18': 118,
 'defense': 3386,
 'including': 5971,
 'one': 8094,
 'arm': 1234,
 'kurds': 6649,
 'fight': 4691,
 'david': 3271,
 'cicilline': 2471,
 'responsible': 9773,
 'loan': 6972,
 'guarantee': 5373,
 'solyndra': 10714,
 'failed': 4537,
 'solar': 10692,
 'company': 2700,
 'ohio': 8069,
 'item': 6336,
 'later': 6723,
 'signed': 10534,
 'gov': 5257,
 'kasich': 6506,
 'requires': 9723,
 'seeking': 10287,
 'abortion': 645,
 'undergo': 11963,
 'mandatory': 7159,
 'vaginal': 12147,
 'probe': 9028,
 'director': 3647,
 'homeland': 5703,
 'cannot': 2154,
 'use': 12110,
 'terrorist': 11470,
 'attack': 1328,
 'instead': 6138,
 'substitutes': 11135,
 'man': 7145,
 'disaster': 3667,
 '51': 440,
 'hispanic': 5656,
 '36': 357,
 'obamacare': 7984,
 'provide': 9169,
 'insurance': 6156,
 'non': 7903,
 'residents': 9748,
 'illegally': 5871,
 'barack': 1503,
 'exactly': 4366,
 'none': 7909,
 'deficit': 3391,
 'reduction': 9507,
 'commissions': 2669,
 'ideas': 5846,
 'changed': 2358,
 'rules': 10008,
 'engagement': 4209,
 'probably': 9025,
 'capt': 2174,
 'humayun': 5795,
 'khans': 6559,
 'life': 6897,
 '2005': 215,
 'co': 2585,
 'sponsored': 10835,
 'would': 12637,
 'jail': 6350,
 'flag': 4783,
 'burners': 2033,
 'paperback': 8355,
 'edition': 4034,
 'romneys': 9957,
 'book': 1820,
 'deleted': 3423,
 'line': 6939,
 'individual': 6028,
 'model': 7570,
 'country': 3037,
 'maggie': 7102,
 'hassan': 5522,
 'tuition': 11866,
 'terry': 11473,
 'mcauliffe': 7297,
 'invented': 6232,
 'scheme': 10185,
 'rent': 9657,
 'lincoln': 6935,
 'bedroom': 1591,
 'created': 3090,
 '800': 549,
 'jobs': 6415,
 'half': 5438,
 'york': 12687,
 'state': 10929,
 'private': 9013,
 'sector': 10273,
 'ever': 4348,
 'towns': 11698,
 'west': 12460,
 'truck': 11841,
 'georgia': 5139,
 'earn': 3993,
 '82': 558,
 'cents': 2310,
 'dollar': 3812,
 'earned': 3994,
 'system': 11316,
 'verifies': 12188,
 'employees': 4151,
 'authorized': 1378,
 'inaccurate': 5946,
 'anywhere': 1130,
 '50': 433,
 'way': 12403,
 'excess': 4383,
 'build': 1997,
 'wall': 12329,
 'ago': 883,
 'long': 7004,
 'like': 6913,
 '06': 13,
 'couldnt': 3018,
 'environmental': 4261,
 'impact': 5898,
 'statements': 10933,
 'sen': 10321,
 'campaign': 2121,
 'announced': 1093,
 'choosing': 2443,
 'cabinet': 2080,
 '2008': 218,
 '54': 452,
 'latinos': 6729,
 'registered': 9553,
 '35': 350,
 'turned': 11877,
 'public': 9191,
 'high': 5629,
 'schools': 10199,
 'offer': 8045,
 'pe': 8483,
 'classes': 2515,
 'republican': 9705,
 'candidate': 2145,
 'around': 1244,
 'military': 7473,
 'recruiters': 9481,
 'harvard': 5510,
 'elena': 4090,
 'kagan': 6495,
 'position': 8834,
 'ruled': 10007,
 'unanimously': 11937,
 'wrong': 12657,
 '321': 331,
 '092': 19,
 'school': 10196,
 'teachers': 11393,
 '313': 324,
 '850': 570,
 'mayor': 7292,
 'providence': 9171,
 'sanctuary': 10084,
 'transgender': 11745,
 'individuals': 6030,
 'chance': 2354,
 'murdered': 7705,
 'bain': 1459,
 'capital': 2167,
 'helped': 5591,
 'early': 3988,
 'childhood': 2426,
 'learning': 6782,
 'called': 2107,
 'bright': 1933,
 'horizons': 5741,
 'lady': 6672,
 'michelle': 7445,
 'rightly': 9880,
 'praised': 8879,
 'rushed': 10020,
 'dayton': 3278,
 'chatter': 2385,
 'social': 10674,
 'media': 7346,
 'posts': 8849,
 'phil': 8611,
 'gingrey': 5177,
 'gave': 5095,
 'power': 8868,
 'electronically': 4086,
 'spy': 10860,
 'without': 12578,
 'warrant': 12359,
 'alex': 948,
 'sink': 10560,
 'funneled': 5029,
 'quarters': 9257,
 'dollars': 3813,
 'bid': 1682,
 'contracts': 2920,
 'take': 11334,
 'population': 8807,
 'virginia': 12252,
 'net': 7831,
 'zero': 12720,
 'job': 6412,
 'creation': 3095,
 'bob': 1787,
 'mcdonnell': 7309,
 'home': 5701,
 'values': 12160,
 'florida': 4816,
 'collapsed': 2614,
 'construction': 2873,
 'foreclosure': 4874,
 'arizona': 1228,
 'immigration': 5893,
 'police': 8759,
 'officer': 8052,
 'stop': 11017,
 'anyone': 1126,
 'appears': 1159,
 'reasonably': 9421,
 'suspicious': 11266,
 'undocumented': 11983,
 'war': 12342,
 'ii': 5866,
 'single': 10559,
 'biggest': 1690,
 'factor': 4527,
 'driving': 3922,
 'recession': 9446,
 'consumer': 2881,
 'native': 7775,
 'perversity': 8585,
 'begun': 1604,
 'save': 10119,
 'savings': 10123,
 'whether': 12486,
 'nominee': 7901,
 'forthcoming': 4903,
 'confirmation': 2800,
 'hearings': 5560,
 'homeless': 5704,
 'veteran': 12199,
 'charlie': 2377,
 'crist': 3121,
 'cuts': 3207,
 'medicare': 7351,
 'advantage': 815,
 'program': 9070,
 'think': 11548,
 'unacceptable': 11932,
 'chinese': 2436,
 'larger': 6711,
 'wind': 12534,
 'panels': 8348,
 'photovoltaic': 8634,
 'manufacturing': 7182,
 'europe': 4330,
 'put': 9235,
 'together': 11630,
 'forget': 4889,
 'brown': 1965,
 'let': 6846,
 'employers': 4154,
 'deny': 3467,
 'coverage': 3055,
 'birth': 1718,
 'point': 8748,
 'lives': 6964,
 'past': 8426,
 '20': 207,
 'egypt': 4059,
 'great': 5316,
 'strides': 11065,
 'democratic': 3442,
 'amount': 1049,
 'attention': 1341,
 'paid': 8321,
 'week': 12435,
 'chris': 2448,
 'christie': 2454,
 'makes': 7126,
 'benghazi': 1642,
 'pale': 8331,
 'significance': 10537,
 'steve': 10988,
 'southerland': 10751,
 'voted': 12290,
 'keep': 6523,
 'perrys': 8568,
 'import': 5917,
 'nurses': 7968,
 'countries': 3036,
 'criminal': 3113,
 'crime': 3110,
 'transport': 11757,
 'dentures': 3465,
 'across': 733,
 'lines': 6941,
 'built': 2000,
 'prison': 9006,
 'days': 3277,
 '1990': 193,
 'mass': 7246,
 'incarceration': 5955,
 'explosion': 4472,
 'nonviolent': 7918,
 'offenders': 8040,
 'plan': 8692,
 'provides': 9175,
 'virtually': 12256,
 'nothing': 7939,
 'burdened': 2016,
 'fastest': 4592,
 'growing': 5364,
 'increases': 5988,
 'major': 7121,
 'phoenix': 8621,
 'kidnapping': 6571,
 'belong': 1621,
 'afl': 858,
 'cio': 2476,
 'commissioner': 2667,
 'cant': 2155,
 'squat': 10866,
 'poll': 8777,
 'found': 4915,
 'could': 3017,
 'beat': 1576,
 'eight': 4062,
 'points': 8750,
 'ronald': 9959,
 'reagan': 9408,
 'sent': 10337,
 'troops': 11833,
 'conflict': 2807,
 'circumstance': 2482,
 'grenada': 5336,
 'peacekeeping': 8486,
 'setting': 10377,
 'lebanon': 6790,
 'jolly': 6433,
 'privatizing': 9017,
 'us': 12104,
 'lowest': 7052,
 'depression': 3496,
 'average': 1396,
 'student': 11088,
 'pocket': 8743,
 'universities': 12021,
 'much': 7687,
 'spend': 10803,
 'cellphones': 2295,
 '1968': 171,
 'died': 3606,
 'gunfire': 5401,
 'wars': 12364,
 'countrys': 3038,
 'effect': 4047,
 '2013': 225,
 'mean': 7325,
 'bill': 1696,
 'facing': 4525,
 'millions': 7484,
 'modified': 7580,
 'mortgage': 7637,
 'short': 10483,
 'sale': 10065,
 'lender': 6829,
 'department': 3471,
 'agricultures': 893,
 'website': 12427,
 'freshfromflorida': 4970,
 'com': 2640,
 'used': 12111,
 'permit': 8559,
 'carry': 2213,
 'loaded': 6970,
 'hidden': 5626,
 'gun': 5400,
 'leaving': 6789,
 'house': 5767,
 'streetcar': 11050,
 'expected': 4439,
 'create': 3089,
 '930': 594,
 'totaling': 11674,
 '600': 473,
 'raising': 9332,
 'minimum': 7502,
 'wage': 12307,
 'hour': 5763,
 'help': 5590,
 'lift': 6905,
 'secretary': 10269,
 'kerry': 6550,
 'senator': 10323,
 'flew': 4797,
 'managua': 7153,
 'met': 7416,
 'communist': 2687,
 'dictator': 3601,
 'daniel': 3250,
 'ortega': 8175,
 'accused': 712,
 'engaging': 4210,
 'terrorism': 11469,
 'nato': 7776,
 'opening': 8105,
 'terror': 11468,
 'division': 3777,
 'im': 5878,
 'sure': 11225,
 'largely': 6710,
 'saying': 10129,
 'criticism': 3126,
 'always': 1013,
 'prochoice': 9041,
 'rating': 9380,
 'gina': 5176,
 'raimondo': 9321,
 'office': 8050,
 'investment': 6248,
 'fees': 4642,
 'pension': 8523,
 'portfolio': 8820,
 'gone': 5232,
 'annually': 1098,
 'day': 3274,
 'obamas': 7990,
 'longer': 7005,
 'lay': 6759,
 'firefighters': 4751,
 'officers': 8053,
 '98': 606,
 '53': 449,
 'old': 8079,
 'thirds': 11551,
 'wisconsinites': 12559,
 'receiving': 9442,
 'checks': 2397,
 'required': 9720,
 'search': 10251,
 'current': 3193,
 'exemptions': 4409,
 'reforms': 9530,
 'premium': 8933,
 'family': 4566,
 'go': 5214,
 '500': 434,
 'per': 8532,
 'irs': 6292,
 'also': 1002,
 'investigated': 6242,
 'liberal': 6868,
 'groups': 5360,
 'progressive': 9073,
 'name': 7744,
 'looking': 7011,
 'everybody': 4352,
 'promised': 9094,
 'creating': 3093,
 'pace': 8303,
 '1999': 203,
 'meet': 7362,
 'prime': 8994,
 'minister': 7505,
 'benjamin': 1643,
 'netanyahu': 7832,
 'majority': 7123,
 'marry': 7223,
 'freely': 4961,
 'love': 7043,
 'say': 10127,
 'reps': 9702,
 'peter': 8591,
 'defazio': 3375,
 'earl': 3985,
 'blumenauer': 1776,
 'socialists': 10677,
 'openly': 8107,
 'serving': 10366,
 'congress': 2819,
 'rudy': 10000,
 'giuliani': 5185,
 'underqualified': 11972,
 'seek': 10286,
 'presidency': 8955,
 'presidents': 8959,
 'governors': 5265,
 'senators': 10324,
 'britains': 1940,
 'leave': 6787,
 'european': 4331,
 'union': 12012,
 'within': 12576,
 'hours': 5766,
 '401': 383,
 'medicaid': 7348,
 'declined': 3340,
 '2012': 224,
 'second': 10261,
 '47': 419,
 '88': 580,
 'constables': 2860,
 'duty': 3976,
 'prepaid': 8937,
 'college': 2629,
 'columbus': 2637,
 '41': 387,
 'contribute': 2925,
 'guaranteed': 5374,
 'check': 2394,
 'pensions': 8524,
 'cfo': 2326,
 'shut': 10511,
 'krakow': 6638,
 'scam': 10168,
 'refunded': 9536,
 'josephine': 6445,
 'victims': 12214,
 'con': 2749,
 'getting': 5154,
 'computer': 2747,
 'sciences': 10205,
 'degrees': 3409,
 '80s': 553,
 'plus': 8738,
 'air': 908,
 'force': 4864,
 'taxpayers': 11387,
 'fund': 5015,
 'fantasy': 4573,
 'football': 4857,
 'league': 6771,
 'hussein': 5818,
 'courts': 3052,
 'accept': 679,
 'islamic': 6306,
 'sharia': 10420,
 'domestic': 3821,
 'disputes': 3736,
 'murders': 7707,
 'committed': 2673,
 'guns': 5402,
 'legally': 6805,
 'purchase': 9216,
 'neighborhood': 7822,
 'closing': 2569,
 'told': 11635,
 'gay': 5098,
 'organizers': 8162,
 'stronger': 11077,
 'advocate': 829,
 'special': 10783,
 'rights': 9881,
 'ted': 11415,
 'kennedy': 6537,
 'speaker': 10778,
 'consistently': 2856,
 'offered': 8046,
 'leaner': 6777,
 'budgets': 1991,
 'halfway': 5439,
 '2010': 222,
 'goal': 5215,
 '700': 507,
 'seven': 10382,
 'saysmichael': 10148,
 'bennet': 1644,
 'close': 2564,
 'guantanamo': 5372,
 'bay': 1564,
 'prisonand': 9007,
 'bring': 1935,
 'terrorists': 11471,
 'colorado': 2635,
 'oregonians': 8152,
 'amazing': 1018,
 'donations': 3834,
 'hes': 5613,
 '250': 286,
 'syrian': 11312,
 'iraqi': 6282,
 'refugees': 9533,
 'research': 9729,
 'shows': 10502,
 'vast': 12169,
 'arriving': 1251,
 'immigrants': 5889,
 'believe': 1615,
 'source': 10747,
 'prosperity': 9142,
 'thats': 11506,
 'support': 11211,
 'newt': 7865,
 'gingrichs': 5179,
 'offers': 8049,
 'doorway': 3849,
 'amnesty': 1045,
 'mr': 7678,
 'caprio': 2172,
 'career': 2191,
 'politician': 8772,
 'rhode': 9848,
 'island': 6310,
 'temporary': 11438,
 'disability': 3652,
 'jersey': 6389,
 '17': 103,
 'interest': 6182,
 'exceed': 4374,
 'revenue': 9827,
 'money': 7598,
 'street': 11049,
 'anybody': 1123,
 'donald': 3827,
 'proliferation': 9089,
 'ok': 8073,
 'taken': 11335,
 'lobbyists': 6981,
 'expressly': 4485,
 'bans': 1499,
 'racial': 9290,
 'profiling': 9064,
 'begging': 1599,
 'send': 10325,
 'coast': 2591,
 'guard': 5377,
 'patrol': 8448,
 'lakes': 6679,
 'mexico': 7435,
 'border': 1836,
 'va': 12131,
 ...}

In [13]:
len(tfidf_V.get_feature_names())

12735

#### Importing the dataset containing the polarity and subjectivity of the datasets

In [14]:
train_pol_sub = pd.read_csv('./datasets/train_pol_sub.csv')
valid_pol_sub = pd.read_csv('./datasets/valid_pol_sub.csv')
test_pol_sub = pd.read_csv('./datasets/test_pol_sub.csv')

Viewing random samples

In [15]:
train_pol_sub.sample(5)

      polarity  subjectivity
8727    -0.100         0.433
6578     0.000         0.000
8904     0.417         0.583
2809     0.000         0.750
2705     0.000         0.000

In [16]:
valid_pol_sub.sample(5)

      polarity  subjectivity
1008     0.188         0.313
120      0.000         0.000
1211     0.000         0.000
484     -0.063         0.375
138      0.175         0.450

In [17]:
test_pol_sub.sample(5)

      polarity  subjectivity
879      0.150         0.050
658      0.000         0.000
1178     0.054         0.637
590     -0.125         0.375
1117     0.167         0.333

In [18]:
print('Train dataset for polarity and subjectivity size: {}'.format(train_pol_sub.shape))
print('Valid dataset for polarity and subjectivity size: {}'.format(valid_pol_sub.shape))
print('Test dataset for polarity and subjectivity size: {}'.format(test_pol_sub.shape))

Train dataset for polarity and subjectivity size: (10240, 2)
Valid dataset for polarity and subjectivity size: (1284, 2)
Test dataset for polarity and subjectivity size: (1267, 2)

Combining train_pol_sub and valid_pol_sub into a single training set as GridSearchCV with 5 fold cross validation will be used for hyperparameter tuning the different models

In [19]:
training_set_pol_sub = pd.concat([train_pol_sub, valid_pol_sub], ignore_index=True)
training_set = pd.concat([training_set, training_set_pol_sub], axis=1)
test_set = pd.concat([test_data, test_pol_sub], axis=1)

In [20]:
print('Training set size: {}'.format(training_set.shape))
training_set.head()

Training set size: (11524, 4)

,label,news,polarity,subjectivity
0,False,Says the Annies List political group supports ...,0.0,0.1
1,True,When did the decline of coal start? It started...,0.1,0.4
2,True,"Hillary Clinton agrees with John McCain ""by vo...",0.0,0.0
3,False,Health care reform legislation is likely to ma...,0.2,0.9
4,True,The economic turnaround started at the end of ...,0.2,0.2

In [21]:
print('Training set size: {}'.format(test_set.shape))
test_set.head()

Training set size: (1267, 4)

,label,news,polarity,subjectivity
0,True,Building a wall on the U.S.-Mexico border will...,0.00,0.000
1,False,Wisconsin is on pace to double the number of l...,0.00,0.000
2,False,Says John McCain has done nothing to help the ...,0.00,0.000
3,True,Suzanne Bonamici supports a plan that will cut...,0.00,0.000
4,False,When asked by a reporter whether hes at the ce...,-0.25,0.325

#### Creating custom transformer for creating meta data for the datasets

In [22]:
class CreateMetaData(BaseEstimator, TransformerMixin):
    """Class to create meta data about the news. The following meta datas
    are created:
    1. polarity
    2. subjectivity
    3. number of capital letters
    4. number of words in news
    5. number of punctuations
    6. number of definite article (the)
    7. number of indefinite articles (a/an)
    8. ratio of capital letters to the number of words
    9. number of quotes in the sentence
    """
    
    def __init__(self, pol_sub=True):
        self.pol_sub = pol_sub
        
    def count_occurence_word(self, statement, words):
        """Function to count the occurence of the word in the statement.
        
        Parameters:
        -----------
        statement: string
            The statement in which the occurence of the word is to be
            counted.
            
        words: list
            The words whose occurence is to be counted.
            
        Returns:
        --------
        count: integer
            The number of occurences of word in the statement.
        """
        count = 0
        for word in words:
            count = count + re.sub(r'[%s]'%(string.punctuation), " ", statement).lower().split().count(word)
        return count
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):        
        number_capital_letter = X['news'].apply(lambda x: len(re.findall(r'[A-Z]', x)))
        number_of_words = X['news'].apply(lambda x: len(x.split()))
        number_of_punctuations = X['news'].apply(lambda x: len(re.findall('[%s]'%(string.punctuation), x)))
        number_of_definite = X['news'].apply(lambda x: self.count_occurence_word(x, ['the']))
        number_of_indefinite = X['news'].apply(lambda x: self.count_occurence_word(x, ['an', 'a']))
        ratio_capital_words = round(number_capital_letter / number_of_words, 3)
        number_of_quotes = (X['news'].str.count('"') + X['news'].str.count("'")) //2
        
        if self.pol_sub:
            return np.c_[number_capital_letter, number_of_words, number_of_punctuations, number_of_definite,
                     number_of_indefinite, ratio_capital_words, number_of_quotes, X['polarity'], 
                     X['subjectivity']]
        else:
            return np.c_[number_capital_letter, number_of_words, number_of_punctuations, number_of_definite,
                         number_of_indefinite, ratio_capital_words, number_of_quotes]

In [23]:
class ItemSelector(BaseEstimator, TransformerMixin):
    """Class to select particular columns from the dataframe.
    """
    
    def __init__(self, keys):
        self.keys = keys
        
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):   
        return X[self.keys]

In [24]:
class Converter(BaseEstimator, TransformerMixin):
    """Class to convert 2d output of ItemSelector to 1d
    """
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):
        return X.values.ravel()

#### Building and tuning Logistic Regression Pipeline

In [25]:
# lr_pipeline = Pipeline([
#     ('lr_union', FeatureUnion([
#         ('meta_data', CreateMetaData()),
#         ('tfidf', Pipeline([
#             ('item_selector', ItemSelector(['news'])),
#             ('converter', Converter()),
#             ('TF', TfidfVectorizer(stop_words=stopwords_list, use_idf=True, smooth_idf=True))
#         ]))
#     ])),
#     ('lr_clf', LogisticRegression(random_state=42, n_jobs=-1))
# ])

In [26]:
# param_grid = {
#     'lr_union__meta_data__pol_sub': [True, False],
#     'lr_union__tfidf__TF__lowercase': [True, False],
#     'lr_union__tfidf__TF__ngram_range': [(1, 1), (1, 2), (1, 3), (1, 4), (1, 5)],
#     'lr_clf__C': [0.0001, 0.001, 0.01, 0.1, 1, 10, 100]
# }

# lr_gs = GridSearchCV(lr_pipeline, param_grid, scoring='f1', cv=5, verbose=1, n_jobs=-1)
# lr_gs.fit(training_set, training_set['label'])

In [27]:
# lr_gs.best_score_

In [28]:
# lr_gs.best_params_

In [29]:
lr_pipeline = Pipeline([
    ('lr_union', FeatureUnion([
        ('meta_data', CreateMetaData(pol_sub=False)),
        ('tfidf', Pipeline([
            ('item_selector', ItemSelector(['news'])),
            ('converter', Converter()),
            ('TF', TfidfVectorizer(lowercase=True, ngram_range=(1, 1), stop_words=stopwords_list, use_idf=True, smooth_idf=True))
        ]))
    ])),
    ('lr_clf', LogisticRegression(C=0.0001, random_state=42, n_jobs=-1))
])

In [30]:
lr_pipeline.fit(training_set, training_set['label'])

Pipeline(memory=None,
     steps=[('lr_union', FeatureUnion(n_jobs=None,
       transformer_list=[('meta_data', CreateMetaData(pol_sub=False)), ('tfidf', Pipeline(memory=None,
     steps=[('item_selector', ItemSelector(keys=['news'])), ('converter', Converter()), ('TF', TfidfVectorizer(analyzer='word', binary=False, decode_er..., penalty='l2', random_state=42,
          solver='warn', tol=0.0001, verbose=0, warm_start=False))])

In [31]:
show_eval_scores(lr_pipeline, test_set, 'Logistic Regression TFIDF Vectorizer with meta data')

Report for ---> Logistic Regression TFIDF Vectorizer with meta data
Accuracy is: 0.5730071033938438
F1 score is: 0.7136050820539969
Precision score is: 0.5736170212765958
Recall score is: 0.9439775910364145

#### Building and Tuning Naive Bayes pipeline

In [32]:
# nb_pipeline = Pipeline([
#     ('nb_union', FeatureUnion([
#         ('meta_data', CreateMetaData(pol_sub=False)),
#         ('tfidf', Pipeline([
#             ('item_selector', ItemSelector(['news'])),
#             ('converter', Converter()),
#             ('TF', TfidfVectorizer(stop_words=stopwords_list, use_idf=True, smooth_idf=True))
#         ]))
#     ])),
#     ('nb_clf', MultinomialNB())
# ])

In [33]:
# param_grid = {
#     'nb_union__tfidf__TF__lowercase': [True, False],
#     'nb_union__tfidf__TF__ngram_range': [(1, 1), (1, 2), (1, 3), (1, 4), (1, 5)],
#     'nb_clf__alpha': [i/10.0 for i in range(18, 32)]
# }

# nb_gs = GridSearchCV(nb_pipeline, param_grid, scoring='f1', cv=5, verbose=1, n_jobs=-1)
# nb_gs.fit(training_set, training_set['label'])

In [34]:
# nb_gs.best_score_

In [35]:
# nb_gs.best_params_

In [36]:
nb_pipeline = Pipeline([
    ('nb_union', FeatureUnion([
        ('meta_data', CreateMetaData(pol_sub=False)),
        ('tfidf', Pipeline([
            ('item_selector', ItemSelector(['news'])),
            ('converter', Converter()),
            ('TF', TfidfVectorizer(lowercase=True, ngram_range=(1, 1), stop_words=stopwords_list, use_idf=True, smooth_idf=True))
        ]))
    ])),
    ('nb_clf', MultinomialNB(alpha=1.9))
])

In [37]:
nb_pipeline.fit(training_set, training_set['label'])

Pipeline(memory=None,
     steps=[('nb_union', FeatureUnion(n_jobs=None,
       transformer_list=[('meta_data', CreateMetaData(pol_sub=False)), ('tfidf', Pipeline(memory=None,
     steps=[('item_selector', ItemSelector(keys=['news'])), ('converter', Converter()), ('TF', TfidfVectorizer(analyzer='word', binary=False, decode_er... transformer_weights=None)), ('nb_clf', MultinomialNB(alpha=1.9, class_prior=None, fit_prior=True))])

In [38]:
show_eval_scores(nb_pipeline, test_set, 'Naive Bayes TFIDF Vectorizer with meta data')

Report for ---> Naive Bayes TFIDF Vectorizer with meta data
Accuracy is: 0.5951065509076559
F1 score is: 0.7249329758713138
Precision score is: 0.5873153779322329
Recall score is: 0.9467787114845938

#### Building and tuning SVM classifier

In [39]:
# svm_pipeline = Pipeline([
#     ('svm_union', FeatureUnion([
#         ('meta_data', CreateMetaData()),
#         ('tfidf', Pipeline([
#             ('item_selector', ItemSelector(['news'])),
#             ('converter', Converter()),
#             ('TF', TfidfVectorizer(stop_words=stopwords_list, use_idf=True, smooth_idf=True))
#         ]))
#     ])),
#     ('svm_clf', SVC(kernel='rbf', random_state=42))
# ])

In [40]:
# param_grid = {
#     'svm_union__tfidf__TF__lowercase': [True, False],
#     'svm_union__meta_data__pol_sub': [True, False],
#     'svm_union__tfidf__TF__ngram_range': [(1, 1), (1, 2), (1, 3), (1, 4), (1, 5)],
#     'svm_clf__gamma': [i/10.0 for i in range(14, 18)]
# }

# svm_gs = GridSearchCV(svm_pipeline, param_grid, scoring='f1', n_jobs=-1, cv=5, verbose=1)
# svm_gs.fit(training_set, training_set['label'])

In [41]:
# svm_gs.best_score_

In [42]:
# svm_gs.best_params_

In [43]:
svm_pipeline = Pipeline([
    ('svm_union', FeatureUnion([
        ('meta_data', CreateMetaData()),
        ('tfidf', Pipeline([
            ('item_selector', ItemSelector(['news'])),
            ('converter', Converter()),
            ('TF', TfidfVectorizer(lowercase=True, ngram_range=(1, 4), stop_words=stopwords_list, use_idf=True, smooth_idf=True))
        ]))
    ])),
    ('svm_clf', SVC(gamma=1.7, kernel='rbf', random_state=42))
])

In [44]:
svm_pipeline.fit(training_set, training_set['label'])

Pipeline(memory=None,
     steps=[('svm_union', FeatureUnion(n_jobs=None,
       transformer_list=[('meta_data', CreateMetaData(pol_sub=True)), ('tfidf', Pipeline(memory=None,
     steps=[('item_selector', ItemSelector(keys=['news'])), ('converter', Converter()), ('TF', TfidfVectorizer(analyzer='word', binary=False, decode_er...f',
  max_iter=-1, probability=False, random_state=42, shrinking=True,
  tol=0.001, verbose=False))])

In [45]:
show_eval_scores(svm_pipeline, test_set, 'SVM TFIDF Vectorizer with meta data')

Report for ---> SVM TFIDF Vectorizer with meta data
Accuracy is: 0.5666929755327546
F1 score is: 0.7203260315843096
Precision score is: 0.566052842273819
Recall score is: 0.9901960784313726

#### Building a Voting Classifier using the above created models

In [46]:
lr_voting_pipeline = Pipeline([
    ('lr_union', FeatureUnion([
        ('meta_data', CreateMetaData(pol_sub=False)),
        ('tfidf', Pipeline([
            ('item_selector', ItemSelector(['news'])),
            ('converter', Converter()),
            ('TF', TfidfVectorizer(lowercase=True, ngram_range=(1, 1), stop_words=stopwords_list, use_idf=True, smooth_idf=True))
        ]))
    ])),
    ('lr_clf', LogisticRegression(C=0.0001, random_state=42, n_jobs=-1))
])

In [47]:
nb_voting_pipeline = Pipeline([
    ('nb_union', FeatureUnion([
        ('meta_data', CreateMetaData(pol_sub=False)),
        ('tfidf', Pipeline([
            ('item_selector', ItemSelector(['news'])),
            ('converter', Converter()),
            ('TF', TfidfVectorizer(lowercase=True, ngram_range=(1, 1), stop_words=stopwords_list, use_idf=True, smooth_idf=True))
        ]))
    ])),
    ('nb_clf', MultinomialNB(alpha=1.9))
])

In [48]:
svm_voting_pipeline = Pipeline([
    ('svm_union', FeatureUnion([
        ('meta_data', CreateMetaData()),
        ('tfidf', Pipeline([
            ('item_selector', ItemSelector(['news'])),
            ('converter', Converter()),
            ('TF', TfidfVectorizer(lowercase=True, ngram_range=(1, 4), stop_words=stopwords_list, use_idf=True, smooth_idf=True))
        ]))
    ])),
    ('svm_clf', SVC(gamma=1.7, kernel='rbf', random_state=42, probability=True))
])

In [49]:
voting_classifier = VotingClassifier(estimators=[
    ('lr', lr_voting_pipeline), ('nb', nb_voting_pipeline),
    ('svm', svm_voting_pipeline)], voting='soft', n_jobs=-1)

In [50]:
voting_classifier.fit(training_set, training_set['label'])

VotingClassifier(estimators=[('lr', Pipeline(memory=None,
     steps=[('lr_union', FeatureUnion(n_jobs=None,
       transformer_list=[('meta_data', CreateMetaData(pol_sub=False)), ('tfidf', Pipeline(memory=None,
     steps=[('item_selector', ItemSelector(keys=['news'])), ('converter', Converter()), ('TF', TfidfVecto...,
  max_iter=-1, probability=True, random_state=42, shrinking=True,
  tol=0.001, verbose=False))]))],
         flatten_transform=None, n_jobs=-1, voting='soft', weights=None)

In [51]:
show_eval_scores(voting_classifier, test_set, 'Voting Classifier(soft) TFIDF Vectorizer')

Report for ---> Voting Classifier(soft) TFIDF Vectorizer
Accuracy is: 0.5840568271507498
F1 score is: 0.7224855186940494
Precision score is: 0.5789029535864979
Recall score is: 0.9607843137254902